version: '2'

services:
  seedbox:
    image: linuxserver/transmission:latest
    networks:
      - traefik
    ports:
      - "51413:51413"
    volumes:
      - "multimedia-movies:/downloads/movies"
      - "multimedia-series:/downloads/series"
      - "multimedia-others:/downloads/others"
      - "seedbox-config:/config"
      - "seedbox-watch:/watch"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      - TRANSMISSION_WEB_HOME=/combustion-release/
    labels:
      - "traefik.frontend.rule=Host:seedbox.<DOMAIN_NAME>"
      - "traefik.port=9091"
      - "traefik.backend=seedbox"
    restart: unless-stopped

  plex:
    image: plexinc/pms-docker:latest
    networks:
      - traefik
    ports:
      - "1900:1900/udp"
      - "3005:3005/tcp"
      - "8324:8324/tcp"
      - "32400:32400/tcp"
      - "32410:32410/udp"
      - "32412:32412/udp"
      - "32413:32413/udp"
      - "32414:32414/udp"
      - "32469:32469/tcp"
    environment:
      - PLEX_UID=1000
      - PLEX_GID=1000
      - TZ=Europe/Paris
      - PLEX_CLAIM=xxxxxxx # get it from https://www.plex.tv/claim
    labels:
      - "traefik.frontend.rule=Host:plex.<DOMAIN_NAME>"
      - "traefik.port=32400"
      - "traefik.backend=plex"
    volumes:
      - "multimedia-movies:/data/movies"
      - "multimedia-series:/data/tvshows"
      - "plex-config:/config"
    restart: unless-stopped

  files:
    image: filebrowser/filebrowser
    networks:
      - traefik
    labels:
      - "traefik.frontend.rule=Host:files.<DOMAIN_NAME>"
      - "traefik.port=80"
      - "traefik.backend=files"
    volumes:
      - "multimedia-movies:/srv/multimedia-movies"
      - "multimedia-series:/srv/multimedia-series"
      - "multimedia-others:/srv/multimedia-others"
      - "plex-config:/srv/plex-config"
      - "seedbox-config:/srv/seedbox-config"
      - "seedbox-watch:/srv/seedbox-watch"
    restart: unless-stopped
